### PR TITLE
2DFT, HPLP, HPSS, IMSK, MELO, REP1, REP2, RPCA

### PR DESCRIPTION
**Pull request by ethman**
A bunch of classic and benchmark algorithms using ``nussl``.

### CODE REVIEW

**Comment by faroit** [comment]
Thanks for your submissions. We are really glad to have the nussl implementation submitted to sisec!

It seems the tests don't pass because some files seem to have wrong naming:

* `M.json` should be `M.E.R.C. Music - Knockout.json`
* `Triviul feat.json` should be `Triviul feat. The Fiend - Widow.json`

Same error happened in #6. 
@ethman @Js-Mim were you using the wav decoded version instead of the stems? There was a bug in the io tools that was [fixed](https://github.com/sigsep/sigsep-mus-io/commit/d2d9b473e9737d557acd0fa11a14e7e84312b285) in the latest version.

**Comment by ethman** [comment]
No, that's actually my fault! I added some stuff in nussl to interface with musdb, and in my script for the benchmarking I was a little lazy: `results_file = mixture.file_name.split('.')[0] + '.json'`. I'll upload those name changes right now.

**Comment by faroit** [comment]
great, is this ready then?

**Comment by ethman** [comment]
Okay deleted those files. This is ready to go.

**Comment by faroit** [comment]
looks good. thanks!

**Pull request merged**
