### PR TITLE
MDL1, MDLT

### PR DESCRIPTION
**Pull request by Js-Mim**
Dear organizers,

we would like to submit our results for the current SiSEC.

### CODE REVIEW

**Comment by faroit** [comment]
thanks. Can you please check the [rendered markdown description](https://github.com/Js-Mim/sigsep-mus-2018/blob/657670e3289dc70786cb84b42f7e26103109716a/submissions/MDL1/description.md) there seems to be some weird characters in it.

**Comment by faroit** [comment]
Due to popular demand, we allow to update pull requests until 3rd of April 23:59 UTC±00:00 before we merge it.

**Comment by Js-Mim** [comment]
I removed the weird characters. It still fails on MDLT method.

**Comment by Js-Mim** [comment]
Triviul and M.E.R.C. are causing some nasty outcome!
Problems fixed, please finalize the pull request.
Thanks for your help @faroit !

**Comment by faroit** [comment]
Give thanks to travis ;-)

**Pull request merged**
